// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package terminal

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw4-fractal-flame/internal/domain/fractal_config"
)

// NewMockFractalUsecase creates a new instance of MockFractalUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFractalUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFractalUsecase {
	mock := &MockFractalUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFractalUsecase is an autogenerated mock type for the FractalUsecase type
type MockFractalUsecase struct {
	mock.Mock
}

type MockFractalUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFractalUsecase) EXPECT() *MockFractalUsecase_Expecter {
	return &MockFractalUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockFractalUsecase
func (_mock *MockFractalUsecase) Execute(ctx context.Context, cfg *fractal_config.Config) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *fractal_config.Config) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFractalUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFractalUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *fractal_config.Config
func (_e *MockFractalUsecase_Expecter) Execute(ctx interface{}, cfg interface{}) *MockFractalUsecase_Execute_Call {
	return &MockFractalUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, cfg)}
}

func (_c *MockFractalUsecase_Execute_Call) Run(run func(ctx context.Context, cfg *fractal_config.Config)) *MockFractalUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *fractal_config.Config
		if args[1] != nil {
			arg1 = args[1].(*fractal_config.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFractalUsecase_Execute_Call) Return(err error) *MockFractalUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFractalUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, cfg *fractal_config.Config) error) *MockFractalUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
