// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fractal_usecase_test

import (
	"image"

	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw4-fractal-flame/internal/domain/fractal_config"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/hw4-fractal-flame/internal/domain/pixels"
)

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// GenerateFractal provides a mock function for the type MockGenerator
func (_mock *MockGenerator) GenerateFractal(cfg *fractal_config.Config) *pixels.Pixels {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFractal")
	}

	var r0 *pixels.Pixels
	if returnFunc, ok := ret.Get(0).(func(*fractal_config.Config) *pixels.Pixels); ok {
		r0 = returnFunc(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pixels.Pixels)
		}
	}
	return r0
}

// MockGenerator_GenerateFractal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFractal'
type MockGenerator_GenerateFractal_Call struct {
	*mock.Call
}

// GenerateFractal is a helper method to define mock.On call
//   - cfg *fractal_config.Config
func (_e *MockGenerator_Expecter) GenerateFractal(cfg interface{}) *MockGenerator_GenerateFractal_Call {
	return &MockGenerator_GenerateFractal_Call{Call: _e.mock.On("GenerateFractal", cfg)}
}

func (_c *MockGenerator_GenerateFractal_Call) Run(run func(cfg *fractal_config.Config)) *MockGenerator_GenerateFractal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fractal_config.Config
		if args[0] != nil {
			arg0 = args[0].(*fractal_config.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGenerator_GenerateFractal_Call) Return(pixels1 *pixels.Pixels) *MockGenerator_GenerateFractal_Call {
	_c.Call.Return(pixels1)
	return _c
}

func (_c *MockGenerator_GenerateFractal_Call) RunAndReturn(run func(cfg *fractal_config.Config) *pixels.Pixels) *MockGenerator_GenerateFractal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageSaver creates a new instance of MockImageSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageSaver {
	mock := &MockImageSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageSaver is an autogenerated mock type for the ImageSaver type
type MockImageSaver struct {
	mock.Mock
}

type MockImageSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageSaver) EXPECT() *MockImageSaver_Expecter {
	return &MockImageSaver_Expecter{mock: &_m.Mock}
}

// SaveImage provides a mock function for the type MockImageSaver
func (_mock *MockImageSaver) SaveImage(img image.Image, path string) error {
	ret := _mock.Called(img, path)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(image.Image, string) error); ok {
		r0 = returnFunc(img, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageSaver_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type MockImageSaver_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - img image.Image
//   - path string
func (_e *MockImageSaver_Expecter) SaveImage(img interface{}, path interface{}) *MockImageSaver_SaveImage_Call {
	return &MockImageSaver_SaveImage_Call{Call: _e.mock.On("SaveImage", img, path)}
}

func (_c *MockImageSaver_SaveImage_Call) Run(run func(img image.Image, path string)) *MockImageSaver_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 image.Image
		if args[0] != nil {
			arg0 = args[0].(image.Image)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageSaver_SaveImage_Call) Return(err error) *MockImageSaver_SaveImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageSaver_SaveImage_Call) RunAndReturn(run func(img image.Image, path string) error) *MockImageSaver_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}
